export const SCENE = {
  background: '#F7F5F0',
  floor: {
    color: '#EDE9E3',
    roughness: 0.88,
    metalness: 0.0,
    size: 40,
  },
  sculpture: {
    color: '#E8E2D8',
    roughness: 0.72,
    metalness: 0.04,
    extrudeDepth: 0.28,
    bevelEnabled: true,
    bevelThickness: 0.025,
    bevelSize: 0.018,
    bevelSegments: 4,
    scale: 0.0045,
    yFloor: 0.0,
  },
  lights: {
    ambientIntensity: 1.8,
    ambientColor: '#FFF8F0',
    keyColor: '#FFF5E8',
    keyIntensity: 3.2,
    keyPosition: [4, 8, 5] as [number, number, number],
    fillColor: '#F0F4FF',
    fillIntensity: 1.2,
    fillPosition: [-5, 4, 3] as [number, number, number],
    rimColor: '#FFFFFF',
    rimIntensity: 0.8,
    rimPosition: [0, 6, -6] as [number, number, number],
    shadowMapSize: 1024,
    shadowBias: -0.001,
    shadowRadius: 12,
  },
  dpr: [1, 1.5] as [number, number],
  camera: {
    near: 0.1,
    far: 60,
  },
  transition: {
    duration: 1.5,
    ease: 'power2.inOut',
    reducedMotionDuration: 0.001,
  },
}
