export const SCENE = {
  background: '#F2EFE9',
  floor: {
    color: '#E5E0D8',
    roughness: 0.92,
    metalness: 0.0,
    size: 40,
  },
  sculpture: {
    color: '#A89E8E',
    roughness: 0.82,
    metalness: 0.02,
    extrudeDepth: 0.32,
    bevelEnabled: true,
    bevelThickness: 0.030,
    bevelSize: 0.022,
    bevelSegments: 5,
    curveSegments: 10,
    scale: 0.0062,
    yFloor: 0.0,
  },
  lights: {
    ambientIntensity: 2.2,
    ambientColor: '#FFF6EC',
    keyColor: '#FFFAF0',
    keyIntensity: 5.5,
    keyPosition: [3, 8, 5] as [number, number, number],
    fillColor: '#EEF2FF',
    fillIntensity: 1.4,
    fillPosition: [-5, 3, 4] as [number, number, number],
    rimColor: '#FFFFFF',
    rimIntensity: 0.9,
    rimPosition: [1, 7, -5] as [number, number, number],
    shadowMapSize: 2048,
    shadowBias: -0.0005,
    shadowRadius: 18,
  },
  contactShadow: {
    opacity: 0.28,
    blur: 2.8,
    far: 2.0,
    resolution: 512,
    color: '#7A7060',
  },
  dpr: [1, 1.5] as [number, number],
  camera: {
    near: 0.1,
    far: 60,
  },
  transition: {
    duration: 1.6,
    ease: 'power3.inOut',
    reducedMotionDuration: 0.001,
    revealDuration: 2.2,
    revealEase: 'power2.out',
  },
  parallax: {
    strength: 0.06,
    smoothing: 0.06,
  },
}
